CXXFLAGS = --std=c++20

boom: boom.o puzzle.o firecracker.o
	-$(CXX) $(CXXFLAGS) boom.o puzzle.o firecracker.o -o boom
	@printf "Now type './boom <file of puzzles>' to play the game!\n\n"

firecracker.o: firecracker.cpp *.h
	-$(CXX) $(CXXFLAGS) -c firecracker.cpp -o firecracker.o

boom.o: boom.cpp *.h
	-$(CXX) $(CXXFLAGS) -c boom.cpp -o boom.o

puzzle.o: puzzle.cpp *.h
	-$(CXX) $(CXXFLAGS) -c puzzle.cpp -o puzzle.o

clean:
	rm -f *.o *.gch a.out  boom

